### ISSUE TITLE
Provide a branch for cloud firestore

### ISSUE THREAD

**Issue by hatemhosny** [duncanhunter/AngularFireCourse#1]
Very nice course. Thank you :)

Please consider creating a branch with the code updated to work with angularfire2 v5 integrating cloud firestore.

**Comment by duncanhunter** [comment]
A branch is a great idea.

Exciting times for Firebase and Angularfire and I am in the process of creating some new code and info to share before any release of a new Pluralsight course. 

Thanks for watching the course
