### ISSUE TITLE
AngularFireList - push().then.catch()   problem

### ISSUE THREAD

**Issue by AlanKharebov** [duncanhunter/AngularFireCourse#2]
In your tutorial and code in github, when you work with a list, you are using 
FirebaseListObservable, for example in saveCompany() functions 

companies$: FirebaseListObservable<Company[]>;
saveCompany(company: Company) {
    return this.companies$.push(company)
      .then(_ => console.log('success'))
      .catch(error => console.log(error));
  }

But, latest Firebase, doesn't have FirebaseListObservable anymore and it uses 
AngularFireList

Here new version:
companies: AngularFireList<Company>;
saveCompany(company: Company) {
    this.companies.push(company).
    then(_ => console.log('success'))
    **.catch(error => console.log(error));**  shows error

[ts] Property 'catch' does not exist on type 'PromiseLike<void
  }

Can you provide updated version working with a list.

I am learning AngularFire from you course from plurasight and putting example code with the latest version of  AngularFire here
https://github.com/Adzond/building-apps-with-angularfire-2

Thanks,
Alan Kharebov
Angular Enthusiast

**Comment by duncanhunter** [comment]
Hi

I apologise but the course would be a rewrite with the changes to the syntax to update the code. I am going to leave the course at this version and if I write another course then update.

This sucks I know but this space has changed a lot lately with new Firestore db and version 5 of Angularfire 2 library being so different.

I am happy to link out to a v5 version but will keep the content at v4

**Comment by AlanKharebov** [comment]
thank you,
alan
