### ISSUE TITLE
Update with 5 Version!

### ISSUE THREAD

**Issue by Iamguy84** [duncanhunter/AngularFireCourse#3]
Hi,

This repo is using old version.  Can you please update with latest version?

Thanks

**Comment by duncanhunter** [comment]
Hi

The course is now pinned to the older version for people still developing at this version. I know this sucks but it is such a syntactic change it would be a rewrite of the course.

I will make the note clearer on the top of the repo and apologise if this was not clear. Things have changed fast in this space.
