### ISSUE TITLE
Material design imports are not updated

### ISSUE THREAD

**Issue by loonix** [duncanhunter/AngularFireCourse#4]
Hi,  

MdButtonModule,
  MdCardModule,
  MdInputModule,
  MdToolbarModule,
  MdProgressBarModule,
  MdSelectModule

now is 

  MatButtonModule,
  MatCardModule,
  MatInputModule,
  MatToolbarModule,
  MatProgressBarModule,
  MatSelectModule

Cheers.

**Comment by duncanhunter** [comment]
Hi

Thanks for taking the time to make this suggestion. I currently have not got any immediate plans to update this course as per the note on the front of the repo. 

I apologise for any frustrations.
